/// <reference types="nuxt-api-party" />
// Minimal placeholder; real types are generated by nuxt-api-party during build/dev.
declare module '#nuxt-api-party/jellyfin' {
  // These will be augmented with actual schema-driven types.
  export interface components {}
  export interface paths {}
  export interface operations {}
}
